version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/gfi
    overwrite: yes
    runas: ec2-user

permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 60
